# Generated by Django 3.2.5 on 2021-10-04 18:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='အကြောင်းအရာ', max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='အချက်အလက်များ')),
                ('public_view', models.BooleanField(default=False, help_text='အများပြည်သူကိုပြမည်။')),
                ('date', models.DateTimeField(help_text='ထုတ်ပြန်သည့်ရက်စွဲ')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_title', models.CharField(help_text='စည်းကမ်းချက်အမည်', max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='စည်းကမ်းချက်များ')),
                ('date', models.DateField(help_text='ထုတ်ပြန်သည့်ရက်စွဲ')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure_title', models.CharField(help_text='လုပ်ဆောင်မည့်အကြောင်းအရာခေါင်းစဉ်', max_length=255)),
                ('date', models.DateField(help_text='ထုတ်ပြန်သည့်ရက်စွဲ')),
                ('policy', models.ForeignKey(blank=True, help_text='စည်းကမ်းချက်များရွေးရန် (သို့မဟုတ်) အသစ်လုပ်ရန်', on_delete=django.db.models.deletion.CASCADE, to='app.policy')),
                ('tag', models.ManyToManyField(blank=True, help_text='အမျိုးအစား', to='app.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(help_text='လုပ်ငန်းအမည်', max_length=255)),
                ('content', ckeditor.fields.RichTextField(help_text='လုပ်ငန်းအကြောင်းအရာ')),
                ('my_order', models.PositiveIntegerField(default=0, help_text='ဦးစားပေးအဆင့်သတ်မှတ်ချက်')),
                ('date', models.DateTimeField()),
                ('procedure', models.ForeignKey(help_text='လုပ်ဆောင်မည့်အကြောင်းအရာခေါင်းစဉ်', on_delete=django.db.models.deletion.CASCADE, to='app.procedure')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
